import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Activity, AlertTriangle, ArrowUpRight, ChevronDown, CloudRain, Droplets, Globe2, Menu, Search, Settings2, Wind, X, Zap } from "lucide-react";
import "@/App.css";
import "@/scenario.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const presets = [{ name: "Chennai", lat: 13.0827, lon: 80.2707 }, { name: "Delhi", lat: 28.7041, lon: 77.1025 }, { name: "Mumbai", lat: 19.076, lon: 72.8777 }, { name: "Tokyo", lat: 35.6762, lon: 139.6503 }, { name: "San Francisco", lat: 37.7749, lon: -122.4194 }];

const demoFinancial = { index: 72.4, trend: "elevated", series: [{ label: "00:00", value: 46 }, { label: "04:00", value: 51 }, { label: "08:00", value: 48 }, { label: "12:00", value: 63 }, { label: "16:00", value: 59 }, { label: "20:00", value: 72 }], alerts: [{ title: "Supply Chain Volatility", detail: "Congestion detected at regional transport hubs.", severity: "HIGH" }, { title: "Energy Grid Stress", detail: "Fluctuations in industrial energy delivery.", severity: "MODERATE" }], entities: [{ name: "Global Logix Corp", level: "HIGH" }, { name: "Aether Energy", level: "MED" }, { name: "Titan Fab", level: "LOW" }] };

function format(value, suffix = "") { return value === null || value === undefined ? "—" : `${Math.round(Number(value) * 10) / 10}${suffix}`; }

export default function App() {
  const [location, setLocation] = useState("Chennai");
  const [coords, setCoords] = useState({ lat: 13.0827, lon: 80.2707 });
  const [scenario, setScenario] = useState("normal");
  const [demoMode, setDemoMode] = useState(true);
  const [analysis, setAnalysis] = useState(null);
  const [financial, setFinancial] = useState(demoFinancial);
  const [loading, setLoading] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [error, setError] = useState("");

  const runAnalysis = async (next = {}) => {
    const values = { location, ...coords, demo_mode: demoMode, scenario, ...next };
    setLoading(true); setError("");
    try { const response = await axios.post(`${API}/analyze`, { latitude: values.lat, longitude: values.lon, location_name: values.location, demo_mode: values.demo_mode, scenario: values.scenario }); setAnalysis(response.data); setError(response.data.error_message || ""); }
    catch (e) { setError("Analysis is temporarily unavailable. Demo telemetry remains active."); setAnalysis({ location: { name: values.location }, environment: {}, alerts: [], is_demo_mode: true }); }
    finally { setLoading(false); }
  };

  useEffect(() => { runAnalysis(); axios.get(`${API}/financial`).then((r) => setFinancial(r.data)).catch(() => {}); /* initial load intentionally runs once */ }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const env = analysis?.environment || {};
  const selected = useMemo(() => presets.find((item) => item.name.toLowerCase() === location.toLowerCase()), [location]);
  const submitSearch = () => { const match = selected || location.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/); if (match) { const next = selected ? { lat: selected.lat, lon: selected.lon, location: selected.name } : { lat: Number(match[1]), lon: Number(match[2]), location }; setCoords({ lat: next.lat, lon: next.lon }); setLocation(next.location); runAnalysis(next); } else runAnalysis(); };

  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="#top" data-testid="brand-home"><span className="brand-mark"><Globe2 size={18} /></span><span>SAFE<span>SPHERE</span></span></a><div className="topbar-right" onMouseEnter={() => setMenuOpen(true)} onMouseLeave={() => setMenuOpen(false)}><button className="icon-button" onClick={() => setMenuOpen(!menuOpen)} data-testid="top-right-menu-button" aria-label="Open control menu"><Menu size={19} /></button>{menuOpen && <div className="hover-menu" data-testid="top-right-hover-menu"><button data-testid="menu-settings-button" onClick={() => { const nextMode = !demoMode; setDemoMode(nextMode); runAnalysis({ demo_mode: nextMode }); }}><Settings2 size={15} /> {demoMode ? "Use live telemetry" : "Use demo telemetry"}</button><button data-testid="menu-refresh-button" onClick={submitSearch}><Activity size={15} /> Refresh intelligence</button></div>}</div></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> INTELLIGENCE MODULE: ACTIVE</p><h1>See the signal<br /><em>before it spreads.</em></h1><p className="hero-sub">A live risk intelligence layer for the physical and financial world.</p><div className={`search-box ${loading ? "is-loading" : ""}`}><Search size={20} /><input value={location} onChange={(e) => setLocation(e.target.value)} onKeyDown={(e) => e.key === "Enter" && submitSearch()} placeholder="Search a city or coordinates" data-testid="location-search-input" /><button onClick={submitSearch} disabled={loading} data-testid="location-search-button">{loading ? "Scanning" : "Analyze"}<ArrowUpRight size={16} /></button></div><div className="preset-row">{presets.map((item) => <button className={location === item.name ? "active" : ""} onClick={() => { setLocation(item.name); setCoords({ lat: item.lat, lon: item.lon }); runAnalysis({ location: item.name, lat: item.lat, lon: item.lon }); }} key={item.name} data-testid={`preset-${item.name.toLowerCase().replace(" ", "-")}-button`}>{item.name}</button>)}<label className="scenario-control">SCENARIO<select value={scenario} onChange={(e) => { setScenario(e.target.value); runAnalysis({ scenario: e.target.value }); }} data-testid="hazard-scenario-select"><option value="normal">Normal</option><option value="flood">Flood</option><option value="earthquake">Earthquake</option><option value="cyclone">Cyclone</option></select></label></div>{error && <p className="error-message" data-testid="analysis-error-message">{error}</p>}</div><div className="orbital-visual"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="signal-core"><Globe2 size={64} strokeWidth={1} /><span>0x7F22-SYNC</span></div><div className="visual-caption"><span>SECTOR 07G</span><strong>{analysis?.location?.name || location}</strong><small>LAT {coords.lat.toFixed(4)} / LON {coords.lon.toFixed(4)}</small></div></div></section>
      <section className="telemetry-section"><div className="section-heading"><div><p className="eyebrow">01 / ATMOSPHERIC TELEMETRY</p><h2>Conditions at a glance</h2></div><span className="live-pill" data-testid="telemetry-status"><span className="status-dot" /> {analysis?.is_demo_mode ? (demoMode ? "DEMO STREAM" : "LIVE FALLBACK") : "LIVE STREAM"}</span></div><div className="metric-grid">{[["Temperature", format(env.temperature_c, "°"), "Heat_Map_v2", "gold", <Zap />], ["Wind velocity", format(env.wind_speed_kmh, " km/h"), "Velocity_Sync", "cyan", <Wind />], ["Precipitation", format(env.precipitation_probability, "%"), "Sat_Feed_A1", "cyan", <CloudRain />], ["Air quality", format(env.aqi), "AQ_Core_v4", "white", <Droplets />]].map(([label, value, module, tone, icon]) => <article className="metric" key={label} data-testid={`metric-${label.toLowerCase().replace(" ", "-")}`}><div className={`metric-icon ${tone}`}>{icon}</div><p>{label}</p><strong>{value}</strong><small>{module}</small></article>)}</div></section>
      <section className="risk-section"><div className="risk-map"><div className="section-heading"><div><p className="eyebrow">02 / RISK MAPPING</p><h2>Live grid overlay</h2></div><span className="map-engine">MAP ENGINE / OPENSTREETMAP</span></div><div className="map-visual"><div className="map-grid" /><div className="map-lines" /><div className="map-pin" /><span className="map-label label-a">ORIGIN SYNC: STABLE</span><span className="map-label label-b">TRAVERSE NODES: 04</span><span className="map-label label-c">HEATMAP LAYER: ACTIVE</span><div className="map-coords">LAT: {coords.lat.toFixed(4)} N<br />LON: {Math.abs(coords.lon).toFixed(4)} W</div></div></div><aside className="risk-panel"><p className="eyebrow">CALCULATED RISK</p><div className="risk-level"><span>LOW</span><div className="risk-bars"><i /><i /><i /><i /></div></div><div className="risk-detail"><span>THREAT LEVEL</span><strong data-testid="threat-level">{analysis?.alerts?.length ? "ELEVATED" : "STABLE"}</strong></div><div className="risk-detail"><span>ACTIVE ALERTS</span><strong data-testid="active-alert-count">{analysis?.alerts?.length || 0}</strong></div><button className="protocol-button" onClick={() => setError("Protocol queued — review the active alerts below.")} data-testid="initiate-protocol-button">Initiate protocol <ArrowUpRight size={16} /></button></aside></section>
      <section className="intel-section"><div className="section-heading"><div><p className="eyebrow">03 / FINANCIAL INTELLIGENCE</p><h2>Market impact index</h2></div><span className="index-value" data-testid="financial-index-value">{financial.index} <small>/ 100</small></span></div><div className="intel-grid"><div className="chart-panel"><div className="chart-header"><span>Financial projection</span><span className="trend-up"><ArrowUpRight size={14} /> {financial.trend}</span></div><div className="chart-wrap" data-testid="financial-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={financial.series}><defs><linearGradient id="cyanFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#62e4df" stopOpacity={0.35} /><stop offset="100%" stopColor="#62e4df" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="label" tick={{ fill: "#6f7d8c", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis hide domain={[0, 100]} /><Tooltip contentStyle={{ background: "#111923", border: "1px solid #2b3b4a", color: "#f4f7f8" }} /><Area type="monotone" dataKey="value" stroke="#62e4df" strokeWidth={2} fill="url(#cyanFill)" /></AreaChart></ResponsiveContainer></div></div><div className="intel-list"><div className="list-head">DISRUPTION ALERTS <span>2 ACTIVE</span></div>{financial.alerts.map((item) => <div className="intel-alert" key={item.title}><AlertTriangle size={16} /><div><strong>{item.title}</strong><p>{item.detail}</p></div><span className={item.severity === "HIGH" ? "high" : "moderate"}>{item.severity}</span></div>)}</div><div className="entities"><div className="list-head">HIGH EXPOSURE ENTITIES</div>{financial.entities.map((item) => <div className="entity" key={item.name}><span>{item.name}</span><b className={item.level.toLowerCase()}>{item.level}</b></div>)}</div></div></section>
      <section className="alerts-section"><div className="section-heading"><div><p className="eyebrow">04 / RESPONSE QUEUE</p><h2>Safety alerts</h2></div><span className="alerts-count" data-testid="alerts-summary">{analysis?.alerts?.length || 0} requiring attention</span></div>{analysis?.alerts?.length ? <div className="alerts-list">{analysis.alerts.map((alert, i) => <article className={`alert-card ${alert.severity.toLowerCase()}`} key={`${alert.title}-${i}`} data-testid={`safety-alert-${i}`}><div className="alert-top"><span className="severity">{alert.severity}</span><span>{alert.hazard_type} / {alert.source}</span><b>{alert.priority_score}/100</b></div><h3>{alert.title}</h3><p>{alert.summary}</p><details><summary>Why this signal?</summary><p>{alert.why}</p><ul>{(alert.actions || []).map((action) => <li key={action}>{action}</li>)}</ul></details></article>)}</div> : <div className="empty-state" data-testid="alerts-empty-state"><Activity size={20} /><span>No significant hazards detected. The sphere is monitoring.</span></div>}</section>
    </main><footer><span>SAFE<span>SPHERE</span> / AUTONOMOUS VIGILANCE</span><span>DECISION SUPPORT — NOT AN OFFICIAL WARNING SYSTEM</span></footer>
  </div>;
}