import { useEffect, useState } from "react";
import axios from "axios";
import { Activity, ArrowUpRight, CloudRain, Globe2, Menu, Search, Thermometer, Wind, X } from "lucide-react";
import "@/App.css";
import "@/scenario.css";
import "@/dashboard.css";
import "@/embed-response.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const earth = "https://static.prod-images.emergentagent.com/jobs/4c0ac1c1-af71-4d48-b461-896c5417eaf6/images/fb7df8e46ea80289ebf2ea1cdc1b91194585741933b52ca46aa34022608386ed.jpeg";
const cities = [{ name: "Chennai", lat: 13.0827, lon: 80.2707 }, { name: "Delhi", lat: 28.7041, lon: 77.1025 }, { name: "Mumbai", lat: 19.076, lon: 72.8777 }, { name: "Tokyo", lat: 35.6762, lon: 139.6503 }];
const financialDemo = { index: 72.4, alerts: [{ title: "Rainfall & flooding", detail: "Coastal transport hubs may experience disruption.", region: "South India · East Coast", severity: "HIGH" }, { title: "Heat wave pressure", detail: "Extreme heat may lift energy demand and reduce output.", region: "North India · Inland hubs", severity: "MODERATE" }], entities: [{ name: "Global Logix Corp", region: "Chennai / Port routes", level: "HIGH" }, { name: "Aether Energy", region: "Hyderabad / Grid belt", level: "MED" }, { name: "Titan Fab", region: "Bengaluru / Industrial", level: "LOW" }] };

export default function App() {
  const [location, setLocation] = useState(cities[0]); const [query, setQuery] = useState("Chennai"); const [weather, setWeather] = useState(null); const [financial, setFinancial] = useState(financialDemo); const [loading, setLoading] = useState(true); const [menu, setMenu] = useState(false); const [message, setMessage] = useState("");
  const loadWeather = async (city) => { setLoading(true); try { const r = await axios.get(`${API}/weather?lat=${city.lat}&lon=${city.lon}`); setWeather(r.data); } catch { setMessage("Weather source unavailable. Showing fallback telemetry."); } finally { setLoading(false); } };
  useEffect(() => { loadWeather(location); axios.get(`${API}/financial`).then((r) => setFinancial(r.data)).catch(() => {}); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const search = () => { const city = cities.find((item) => item.name.toLowerCase() === query.trim().toLowerCase()); const coord = query.match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/); const next = city || (coord ? { name: query, lat: Number(coord[1]), lon: Number(coord[2]) } : null); if (!next) return setMessage("Choose a city or enter coordinates as latitude, longitude."); setLocation(next); loadWeather(next); setMessage(""); };
  const current = weather?.current || {};
  return <div className="safe-app"><header className="nav"><a href="#top" className="logo" data-testid="brand-home"><span><Globe2 /></span>SAFE<span>SPHERE</span></a><div className="menu-wrap" onMouseEnter={() => setMenu(true)} onMouseLeave={() => setMenu(false)}><button className="menu-button" onClick={() => setMenu(!menu)} data-testid="top-right-menu-button"><Menu /></button>{menu && <div className="nav-menu" data-testid="top-right-hover-menu"><a href="#weather" data-testid="menu-weather-link">Weather dashboard</a><a href="#map" data-testid="menu-map-link">Live risk map</a><a href="#finance" data-testid="menu-finance-link">Financial intelligence</a></div>}</div></header><main id="top"><section className="opening"><div className="opening-copy"><p className="kicker"><i /> AUTONOMOUS INTELLIGENCE / ONLINE</p><h1>Know what’s<br /><em>coming next.</em></h1><p className="lede">Live signals for weather, risk, and markets — translated into decisions you can act on.</p><div className="location-search"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && search()} placeholder="Search city or coordinates" data-testid="location-search-input" /><button onClick={search} data-testid="location-search-button">Scan <ArrowUpRight size={18} /></button></div><div className="city-pills">{cities.map((city) => <button key={city.name} className={location.name === city.name ? "selected" : ""} onClick={() => { setLocation(city); setQuery(city.name); loadWeather(city); }} data-testid={`city-${city.name.toLowerCase()}-button`}>{city.name}</button>)}</div>{message && <p className="notice" data-testid="user-notice">{message}</p>}</div><div className="earth-stage"><div className="earth-glow" /><div className="spinning-earth" style={{ backgroundImage: `url(${earth})` }} data-testid="spinning-earth" /><div className="earth-orbit orbit-one" /><div className="earth-orbit orbit-two" /><span className="earth-readout">{location.name.toUpperCase()}<small>LIVE LOCATION TARGET</small></span></div></section>
    <section className="feature weather-window" id="weather"><div className="window-heading"><div><p className="kicker">01 / INTELLIGENCE MODULE</p><h2>Weather dashboard</h2><p className="window-sub">Live location-wise conditions for <b>{location.name}</b></p></div><span className="window-status" data-testid="weather-status"><i /> {loading ? "SYNCING" : weather?.status === "live" ? "LIVE" : "FALLBACK"}</span></div><div className="weather-grid"><div className="weather-main"><span className="weather-icon"><CloudRain size={34} /></span><strong data-testid="weather-temperature">{current.temperature_2m ?? "—"}°</strong><span>Current conditions</span><small>{weather?.source || "Open-Meteo"}</small></div><div className="weather-stat"><Thermometer /><span>HUMIDITY</span><b>{current.relative_humidity_2m ?? "—"}%</b></div><div className="weather-stat"><Wind /><span>WIND</span><b>{current.wind_speed_10m ?? "—"} km/h</b></div><div className="weather-stat"><CloudRain /><span>PRECIPITATION</span><b>{current.precipitation ?? "—"} mm</b></div></div></section>
    <section className="feature map-window" id="map"><div className="embedded-window-heading"><div><p className="kicker">02 / LIVE GRID OVERLAY</p><h2>Complete live risk map</h2><p className="window-sub">The live SafeSphere map, embedded exactly as published.</p></div><span className="window-status"><i /> LIVE WEBSITE</span></div><div className="iframe-shell"><iframe src="https://safesphereai-rudt.vercel.app/" title="SafeSphere live risk map" data-testid="safesphere-live-iframe" allow="geolocation" /></div></section>
    <section className="feature finance-window" id="finance"><div className="window-heading"><div><p className="kicker">03 / FINANCIAL INTELLIGENCE</p><h2>Where disruption could land</h2><p className="window-sub">Regional exposure translated into a clear market impact view.</p></div><div className="impact-index" data-testid="financial-index-value"><small>MARKET IMPACT INDEX</small><strong>{financial.index}</strong><span>/ 100 · ELEVATED</span></div></div><div className="finance-blocks"><div className="intel-block"><h3>Recent disruption alerts</h3>{financial.alerts.map((a) => <article key={a.title} data-testid={`financial-alert-${a.title}`}><div className={`alert-dot ${a.severity.toLowerCase()}`} /><div><b>{a.title}</b><p>{a.detail}</p><small>Could land in: {a.region}</small></div><span>{a.severity}</span></article>)}</div><div className="intel-block"><h3>Companies breakdown</h3>{financial.entities.map((e) => <article key={e.name} data-testid={`company-${e.name}`}><div><b>{e.name}</b><p>{e.region}</p></div><strong className={e.level.toLowerCase()}>{e.level} ALERT</strong></article>)}</div></div></section>
    <section className="feature response-window"><div className="response-mark"><Activity size={35} /></div><div><p className="kicker">04 / EMERGENCY RESPONSE</p><h2>Coordinate the next move.</h2><p className="window-sub">A focused response desk for triage, safe-route decisions, and field coordination when a signal becomes an incident.</p><div className="response-subwindow"><span><b>01</b> Verify alert source</span><span><b>02</b> Select response team</span><span><b>03</b> Share safe route</span></div></div><button onClick={() => setMessage("Emergency response protocol queued for review.")} data-testid="initiate-protocol-button">Open response desk <ArrowUpRight size={18} /></button></section></main><footer><span>SAFE<span>SPHERE</span> / AUTONOMOUS VIGILANCE</span><span>DECISION SUPPORT · {new Date().getFullYear()}</span></footer></div>;
}